name: Netlify Github workflow sandbox

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize, closed]

env:
  GITHUB_ENVIRONMENT_NAME: PR_${{ github.event.pull_request.number }}

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  netlify:
    if: github.event_name == 'pull_request' && contains(fromJSON('["opened", "ready_for_review", "reopened"]'), github.event.action)
    runs-on: ubuntu-latest
    environment: PR_${{ github.event.pull_request.number }}
    steps:
    - name: Get allowed branches
      id: get-netlify-branches
      uses: netlify/actions/cli@master
      with:
        args: "api getSite --data '{ \"site_id\": \"${{ secrets.NETLIFY_SITE_ID }}\" }'"
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    - name: Add current branch to Netlify 🌲
      env:
        NETLIFY_SITE_DATA: ${{ steps.get-netlify-branches.outputs.NETLIFY_OUTPUT }}
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        GET_SITE_DATA="{ \"site_id\": \"${NETLIFY_SITE_ID}\" }"
        echo "Get Site Data: $GET_SITE_DATA"
        NETLIFY_SITE_DATA=$(netlify api getSite --data $GET_SITE_DATA)
        echo "Site Data: $NETLIFY_SITE_DATA"
        ALLOWED_BRANCHES=$(jq '.build_settings.allowed_branches' <<< $NETLIFY_SITE_DATA)
        echo "Allowed Branches: ${ALLOWED_BRANCHES}"

        if [ $(jq '.[]|select(index("$BRANCH_NAME"))' <<< "$ALLOWED_BRANCHES") ]; then
          echo "Adding ${BRANCH_NAME} to Netlify allowed_branches"
          UPDATED_ALLOWED_BRANCHES=$(jq '.[] |= .+ "$BRANCH_NAME' <<< "$ALLOWED_BRANCHES")
          echo "Updated Allowed Branches: ${UPDATED_ALLOWED_BRANCHES}"
        fi
